import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'BM';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const translations: Record<Language, Record<string, string>> = {
    EN: {
      'nav.home': 'HOME',
      'nav.events': 'EVENTS',
      'nav.results': 'RESULTS',
      'nav.about': 'ABOUT US',
      'nav.contact': 'GET IN TOUCH',
      'nav.login': 'LOGIN',
      'nav.signup': 'SIGN UP',
      'nav.cart': 'MY CART',
      'hero.subtitle': 'STAY WITH US FOR MORE UPCOMING SPORTS EVENTS',
      'hero.title1': 'EVERY',
      'hero.title2': 'SECOND',
      'hero.title3': 'COUNTS',
      'hero.desc': 'Time Track provides the best sports timing and event management services in Malaysia. Excellence in every millisecond.',
      'hero.cta1': 'Upcoming Events',
      'hero.cta2': 'Login',
      'marquee.text': 'EXAMPLE',
      'events.reg_open': 'Registration Open',
      'events.upcoming': 'UPCOMING',
      'events.events': 'EVENTS',
      'events.desc': 'Secure your spot in the most anticipated races of 2026. Excellence in timing, coordination, and athlete experience.',
      'events.archive': 'EVENT',
      'events.archive_span': 'ARCHIVE',
      'events.view_more': 'View More Events',
      'events_page.title1': 'THE',
      'events_page.title2': 'EVENTS',
      'events_page.desc': 'Discover upcoming challenges and relive major milestones. Use our official registration portal to secure your spot.',
      'about.hero.story': 'Our Story',
      'about.hero.title1': 'DRIVING',
      'about.hero.title2': 'PERFORMANCE',
      'about.hero.desc': 'At Time Track Solution, we are dedicated to simplifying sports through technology. We provide a robust, user-friendly portal designed to streamline the journey from sign-up to the finish line.',
      'about.cta.title': 'SCALABLE. SECURE.',
      'about.cta.title_span': 'UNRELENTING.',
      'about.cta.button': 'JOIN THE TRACK',
      'footer.explore': 'Explore',
      'footer.policy': 'Our Policy',
      'footer.privacy': 'Privacy Policy',
      'footer.refund': 'Return & Refund Policy',
      'footer.copyright': 'Copyright ©2026 Time Track | All Right Reserved',
      'policy.last_updated': 'Last Updated',
      'policy.contact_us': 'Contact Us',
      'policy.overview': 'Overview',
      'privacy.hero': 'Privacy Policy',
      'privacy.pdpa_title': 'PDPA Compliance',
      'privacy.retention': 'Retention',
      'privacy.transfer': 'Transfer',
      'privacy.deletion': 'Deletion',
      'privacy.changes': 'Changes',
      'refund.hero': 'Return & Refund Policy',
      'refund.intro': 'Introduction',
      'refund.cancellation': 'Cancellation Rights',
      'refund.exercise': 'Exercise of Right',
      'refund.process': 'Reimbursement Process',
      'card.open': 'Open',
      'card.archived': 'Archived',
      'card.reg_now': 'Register Now',
      'card.archive_only': 'Archive Only',
      'card.reg_closed': 'Registration Closed',
      'home.precision': 'Lightning Precision',
      'home.precision_desc': 'Providing the most accurate millisecond timing using industry-leading RFID technology.',
      'home.mgmt': 'Event Management',
      'home.mgmt_desc': "From registration to finish line, we ensure a seamless experience for organizers and athletes.",
      'home.results': 'Result Services',
      'home.results_desc': 'Instant live tracking and certified digital results available immediately after completion.',
      'home.ready': 'READY TO',
      'home.dominate': 'DOMINATE',
      'home.field': 'THE FIELD?',
      'contact.title': 'CONTACT US',
      'contact.subtitle': 'HAVE A QUESTION? OUR TEAM IS READY TO ASSIST YOU.',
      'contact.name': 'Name',
      'contact.email': 'Email',
      'contact.message': 'Message',
      'contact.send': 'Send Message',
      'loading.status': 'System_Status: Optimal',
      'loading.init': 'Init. Systems',
      'about.roadmap.1.title': 'Passionate Innovation',
      'about.roadmap.1.desc': 'Simplifying the sports event registration process with cutting-edge technology specifically designed for the modern athlete.',
      'about.roadmap.2.title': 'Scalable Solutions',
      'about.roadmap.2.desc': 'Built with scalability and security in mind, handling everything from local tournaments to large-scale international events.',
      'about.roadmap.3.title': 'Seamless Registration',
      'about.roadmap.3.desc': 'Effortless online registration, category selection, and secure payment processing for a worry-free experience.',
      'about.roadmap.4.title': 'Real-Time Management',
      'about.roadmap.4.desc': 'Instant access to participant information and data management for efficient, millisecond-perfect coordination.',
      'about.roadmap.5.title': 'Dynamic Scheduling',
      'about.roadmap.5.desc': 'Automated notifications and real-time schedule tracking to keep organizers and participants perfectly in sync.',
      'about.roadmap.6.title': 'Insights & Analytics',
      'about.roadmap.6.desc': 'Powerful tools for analyzing registration trends and event performance to ensure every second counts.',
      'login.title': 'WELCOME BACK',
      'login.subtitle': 'Sign in to access your track performance and upcoming races.',
      'login.google': 'Continue with Google',
      'login.or': 'OR CONTINUE WITH',
      'login.email': 'Email Address',
      'login.password': 'Password',
      'login.signin': 'Sign In',
      'login.no_account': "Don't have an account?",
      'login.signup': 'Sign Up',
      'login.organizer_title': 'ORGANIZER ACCESS',
      'login.organizer_warning': 'This section is strictly for authorized organizers only.',
      'signup.title': 'CREATE ACCOUNT',
      'signup.subtitle': 'Join the track and start dominating the field.',
      'signup.name': 'Full Name',
      'signup.already': 'Already have an account?',
      'signup.button': 'Create Account',
      'login.forgot': 'Forgot Password?',
      'login.full_name': 'Full Name',
      'login.confirm_password': 'Confirm Password',
      'forgot.back': 'Back to Login',
      'about.hero.title': 'About Time Track',
      'about.intel.title': 'Our Mission',
      'about.intel.desc': 'Time Track is a modern platform designed to make sports event management easier for everyone.',
      'about.intel.quote': 'We provide a secure and simple system that helps organizers manage events while giving participants a smooth experience.',
      'about.hierarchy.title': 'Access Levels',
      'about.hierarchy.subtitle': 'User Roles & Permissions',
      'about.features.title': 'Our Services',
      'about.features.subtitle': 'Comprehensive Solutions',
      'about.roles.level0': 'Platform Owner',
      'about.roles.level1': 'Administrator',
      'about.roles.level2': 'Event Organizer',
      'about.roles.level3': 'Athlete / User',
      'about.roles.desc0': 'Full control over platform settings and global data management.',
      'about.roles.desc1': 'Governs event approvals and manages day-to-day operations.',
      'about.roles.desc2': 'Creates and manages individual events and race categories.',
      'about.roles.desc3': 'Browses events, registers, and views official race results.',
      'contact.hero.title': 'Get in Touch',
      'contact.hero.desc': 'Have a question? Our team is here to help you.',
      'results.hero.title': 'Race Results',
      'results.hero.desc': 'Find official results, rankings, and digital certificates for your past races.',
      'results.search.placeholder': 'Search by event name or bib number...',
      'results.view.board': 'View Leaderboard',
      'events.no_found': 'No Events Found',
      'events.search_placeholder': 'Search for events or locations...',
      'events.reset': 'Clear Search',
      'results.download_cert': 'Download Certificate',
      'results.participants': 'Participants',
      'contact.label.name': 'Your Full Name',
      'contact.label.email': 'Email Address',
      'contact.label.message': 'How can we help?',
      'contact.button.send': 'Send Message',
      'contact.info.transmission': 'Email Us',
      'contact.info.presence': 'Our Coverage',
      'contact.info.support': 'Support Hours',
      'signup.role.athlete': 'Athlete / Participant',
      'signup.role.organizer': 'Event Organizer',
      'signup.secret': 'Organizer Access Code',
      'signup.secret_placeholder': 'ENTER CLEARANCE CODE',
      'home.cta.ready': 'Ready to Race?',
      'home.cta.join': 'Join the Track'
    },
    BM: {
      'nav.home': 'LAMAN UTAMA',
      'nav.events': 'ACARA',
      'nav.results': 'KEPUTUSAN',
      'nav.about': 'TENTANG KAMI',
      'nav.contact': 'HUBUNGI KAMI',
      'nav.login': 'LOG MASUK',
      'nav.signup': 'DAFTAR',
      'nav.cart': 'TROLI SAYA',
      'hero.subtitle': 'IKUTI KAMI UNTUK LEBIH BANYAK ACARA SUKAN AKAN DATANG',
      'hero.title1': 'SETIAP',
      'hero.title2': 'SAAT',
      'hero.title3': 'BERHARGA',
      'hero.desc': 'Time Track menyediakan perkhidmatan masa sukan dan pengurusan acara terbaik di Malaysia. Kecemerlangan dalam setiap milisaat.',
      'hero.cta1': 'Acara Akan Datang',
      'hero.cta2': 'Log Masuk',
      'marquee.text': 'CONTOH',
      'events.reg_open': 'Pendaftaran Dibuka',
      'events.upcoming': 'ACARA',
      'events.events': 'MENDATANG',
      'events.desc': 'Tempah slot anda dalam perlumbaan yang paling dinantikan pada 2026. Kecemerlangan dalam masa, koordinasi, dan pengalaman atlet.',
      'events.archive': 'ARKIB',
      'events.archive_span': 'ACARA',
      'events.view_more': 'Lihat Lebih Banyak Acara',
      'events_page.title1': 'KALENDAR',
      'events_page.title2': 'ACARA',
      'events_page.desc': 'Temui cabaran akan datang dan hayati semula pencapaian utama. Gunakan portal pendaftaran rasmi kami untuk menempah slot anda.',
      'about.hero.story': 'Kisah Kami',
      'about.hero.title1': 'MEMACU',
      'about.hero.title2': 'PRESTASI',
      'about.hero.desc': 'Di Time Track Solution, kami berdedikasi untuk memudahkan sukan melalui teknologi. Kami menyediakan portal yang teguh dan mesra pengguna yang direka untuk memudahkan perjalanan dari pendaftaran hingga ke garis penamat.',
      'about.cta.title': 'BOLEH SKALA. SELAMAT.',
      'about.cta.title_span': 'TIDAK TERGUGAT.',
      'about.cta.button': 'SERTAI KAMI',
      'footer.explore': 'Teroka',
      'footer.policy': 'Polisi Kami',
      'footer.privacy': 'Polisi Privasi',
      'footer.refund': 'Polisi Pemulangan & Bayaran Balik',
      'footer.copyright': 'Hak Cipta ©2026 Time Track | Semua Hak Terpelihara',
      'policy.last_updated': 'Terakhir Dikemas Kini',
      'policy.contact_us': 'Hubungi Kami',
      'policy.overview': 'Gambaran Keseluruhan',
      'privacy.hero': 'Polisi Privasi',
      'privacy.pdpa_title': 'Pematuhan PDPA',
      'privacy.retention': 'Penyimpanan',
      'privacy.transfer': 'Pemindahan',
      'privacy.deletion': 'Pemadaman',
      'privacy.changes': 'Perubahan',
      'refund.hero': 'Polisi Pemulangan & Bayaran Balik',
      'refund.intro': 'Pengenalan',
      'refund.cancellation': 'Hak Pembatalan',
      'refund.exercise': 'Menjalankan Hak',
      'refund.process': 'Proses Bayaran Balik',
      'card.open': 'Buka',
      'card.archived': 'Arkib',
      'card.reg_now': 'Daftar Sekarang',
      'card.archive_only': 'Arkib Sahaja',
      'card.reg_closed': 'Pendaftaran Ditutup',
      'home.precision': 'Ketepatan Kilat',
      'home.precision_desc': 'Menyediakan catatan masa milisaat paling tepat menggunakan teknologi RFID terkemuka industri.',
      'home.mgmt': 'Pengurusan Acara',
      'home.mgmt_desc': "Dari pendaftaran hingga ke garis penamat, kami memastikan pengalaman yang lancar untuk penganjur dan atlet.",
      'home.results': 'Perkhidmatan Keputusan',
      'home.results_desc': 'Penjejakan langsung segera dan keputusan digital yang diperakui tersedia serta-merta selepas tamat.',
      'home.ready': 'SEDIA UNTUK',
      'home.dominate': 'MENGUASAI',
      'home.field': 'PADANG?',
      'contact.title': 'HUBUNGI KAMI',
      'contact.subtitle': 'ADA PERTANYAAN? PASUKAN KAMI SEDIA MEMBANTU ANDA.',
      'contact.name': 'Nama',
      'contact.email': 'E-mel',
      'contact.message': 'Mesej',
      'contact.send': 'Hantar Mesej',
      'loading.status': 'Status_Sistem: Optimum',
      'loading.init': 'Memulakan Sistem',
      'about.roadmap.1.title': 'Inovasi Bersemangat',
      'about.roadmap.1.desc': 'Memudahkan proses pendaftaran acara sukan dengan teknologi terkini yang direka khas untuk atlet moden.',
      'about.roadmap.2.title': 'Penyelesaian Boleh Skala',
      'about.roadmap.2.desc': 'Dibina dengan skala dan keselamatan dalam fikiran, mengendalikan segala-galanya dari kejohanan tempatan hingga acara antarabangsa berskala besar.',
      'about.roadmap.3.title': 'Pendaftaran Lancar',
      'about.roadmap.3.desc': 'Pendaftaran dalam talian yang mudah, pemilihan kategori, dan pemprosesan pembayaran yang selamat untuk pengalaman tanpa bimbang.',
      'about.roadmap.4.title': 'Pengurusan Masa Nyata',
      'about.roadmap.4.desc': 'Akses segera kepada maklumat peserta dan pengurusan data untuk koordinasi yang tepat pada milisaat.',
      'about.roadmap.5.title': 'Penjadualan Dinamik',
      'about.roadmap.5.desc': 'Pemberitahuan automatik dan penjejakan jadual masa nyata untuk memastikan penganjur dan peserta sentiasa selari.',
      'about.roadmap.6.title': 'Wawasan & Analitik',
      'about.roadmap.6.desc': 'Alatan berkuasa untuk menganalisis trend pendaftaran dan prestasi acara bagi memastikan setiap saat berharga.',
      'login.title': 'SELAMAT KEMBALI',
      'login.subtitle': 'Log masuk untuk akses prestasi larian dan acara akan datang anda.',
      'login.google': 'Teruskan dengan Google',
      'login.or': 'ATAU TERUSKAN DENGAN',
      'login.email': 'Alamat Emel',
      'login.password': 'Kata Laluan',
      'login.signin': 'Log Masuk',
      'login.no_account': "Tiada akaun?",
      'login.signup': 'Daftar Sekarang',
      'login.organizer_title': 'AKSES PENGANJUR',
      'login.organizer_warning': 'Bahagian ini terhad kepada penganjur yang sah sahaja.',
      'signup.title': 'DAFTAR AKAUN',
      'signup.subtitle': 'Sertai larian dan mula menguasai padang.',
      'signup.name': 'Nama Penuh',
      'signup.already': 'Sudah mempunyai akaun?',
      'signup.button': 'Daftar Sekarang',
      'signup.role.athlete': 'Atlet / Peserta',
      'signup.role.organizer': 'Penganjur Acara',
      'signup.secret': 'Kod Akses Penganjur',
      'signup.secret_placeholder': 'MASUKKAN KOD PELEPASAN',
      'login.forgot': 'Lupa Kata Laluan?',
      'login.full_name': 'Nama Penuh',
      'login.confirm_password': 'Sahkan Kata Laluan',
      'forgot.back': 'Kembali ke Log Masuk',
      'about.hero.title': 'Tentang Time Track',
      'about.intel.title': 'Misi Kami',
      'about.intel.desc': 'Time Track adalah platform moden yang direka untuk memudahkan pengurusan acara sukan bagi semua orang.',
      'about.intel.quote': 'Kami menyediakan sistem yang selamat dan mudah untuk membantu penganjur mengurus acara sambil memberi pengalaman lancar kepada peserta.',
      'about.hierarchy.title': 'Tahap Akses',
      'about.hierarchy.subtitle': 'Peranan & Keizinan Pengguna',
      'about.features.title': 'Perkhidmatan Kami',
      'about.features.subtitle': 'Penyelesaian Menyeluruh',
      'about.roles.level0': 'Pemilik Platform',
      'about.roles.level1': 'Pentadbir',
      'about.roles.level2': 'Penganjur Acara',
      'about.roles.level3': 'Atlet / Pengguna',
      'about.roles.desc0': 'Kawalan penuh terhadap tetapan platform dan pengurusan data global.',
      'about.roles.desc1': 'Menguruskan kelulusan acara dan operasi harian.',
      'about.roles.desc2': 'Mencipta dan menguruskan acara serta kategori perlumbaan individu.',
      'about.roles.desc3': 'Melayari acara, mendaftar, dan melihat keputusan perlumbaan rasmi.',
      'contact.hero.title': 'Hubungi Kami',
      'contact.hero.desc': 'Ada soalan? Pasukan kami sedia membantu anda.',
      'results.hero.title': 'Keputusan Perlumbaan',
      'results.hero.desc': 'Cari keputusan rasmi, kedudukan, dan sijil digital untuk perlumbaan anda yang lalu.',
      'results.search.placeholder': 'Cari mengikut nama acara atau nombor bib...',
      'results.view.board': 'Lihat Carta Kedudukan',
      'events.no_found': 'Tiada Acara Dijumpai',
      'events.search_placeholder': 'Cari acara atau lokasi...',
      'events.reset': 'Kosongkan Carian',
      'results.download_cert': 'Muat Turun Sijil',
      'results.participants': 'Peserta',
      'contact.label.name': 'Nama Penuh Anda',
      'contact.label.email': 'Alamat E-mel',
      'contact.label.message': 'Bagaimana kami boleh membantu?',
      'contact.button.send': 'Hantar Mesej',
      'contact.info.transmission': 'E-mel Kami',
      'contact.info.presence': 'Liputan Kami',
      'contact.info.support': 'Waktu Sokongan',
      'home.cta.ready': 'Sedia untuk Berlumbal?',
      'home.cta.join': 'Sertai Kami'
    }
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
