import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'BM';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const translations: Record<Language, Record<string, string>> = {
    EN: {
      'nav.home': 'HOME',
      'nav.events': 'EVENTS',
      'nav.results': 'RESULTS',
      'nav.about': 'ABOUT US',
      'nav.contact': 'GET IN TOUCH',
      'nav.login': 'LOGIN',
      'nav.signup': 'SIGN UP',
      'nav.cart': 'MY CART',
      'hero.subtitle': 'STAY WITH US FOR MORE UPCOMING SPORTS EVENTS',
      'hero.title1': 'EVERY',
      'hero.title2': 'SECOND',
      'hero.title3': 'COUNTS',
      'hero.desc': 'Time Track provides the best sports timing and event management services in Malaysia. Excellence in every millisecond.',
      'hero.cta1': 'Upcoming Events',
      'hero.cta2': 'Login',
      'marquee.text': 'EXAMPLE',
      'events.reg_open': 'Registration Open',
      'events.upcoming': 'UPCOMING',
      'events.events': 'EVENTS',
      'events.desc': 'Secure your spot in the most anticipated races of 2026. Excellence in timing, coordination, and athlete experience.',
      'events.archive': 'EVENT',
      'events.archive_span': 'ARCHIVE',
      'events.view_more': 'View More Events',
      'events_page.title1': 'THE',
      'events_page.title2': 'EVENTS',
      'events_page.desc': 'Discover upcoming challenges and relive major milestones. Use our official registration portal to secure your spot.',
      'about.hero.story': 'Our Story',
      'about.hero.title1': 'DRIVING',
      'about.hero.title2': 'PERFORMANCE',
      'about.hero.desc': 'At Time Track Solution, we are dedicated to simplifying sports through technology. We provide a robust, user-friendly portal designed to streamline the journey from sign-up to the finish line.',
      'about.cta.title': 'SCALABLE. SECURE.',
      'about.cta.title_span': 'UNRELENTING.',
      'about.cta.button': 'JOIN THE TRACK',
      'footer.explore': 'Explore',
      'footer.policy': 'Our Policy',
      'footer.copyright': 'Copyright ©2026 Time Track | All Right Reserved',
      'card.open': 'Open',
      'card.archived': 'Archived',
      'card.reg_now': 'Register Now',
      'card.archive_only': 'Archive Only',
      'card.reg_closed': 'Registration Closed',
      'home.precision': 'Lightning Precision',
      'home.precision_desc': 'Providing the most accurate millisecond timing using industry-leading RFID technology.',
      'home.mgmt': 'Event Management',
      'home.mgmt_desc': "From registration to finish line, we ensure a seamless experience for organizers and athletes.",
      'home.results': 'Result Services',
      'home.results_desc': 'Instant live tracking and certified digital results available immediately after completion.',
      'home.ready': 'READY TO',
      'home.dominate': 'DOMINATE',
      'home.field': 'THE FIELD?',
      'contact.title': 'CONTACT US',
      'contact.subtitle': 'HAVE A QUESTION? OUR TEAM IS READY TO ASSIST YOU.',
      'contact.name': 'Name',
      'contact.email': 'Email',
      'contact.message': 'Message',
      'contact.send': 'Send Message',
      'loading.status': 'System_Status: Optimal',
      'loading.init': 'Init. Systems',
      'about.roadmap.1.title': 'Passionate Innovation',
      'about.roadmap.1.desc': 'Simplifying the sports event registration process with cutting-edge technology specifically designed for the modern athlete.',
      'about.roadmap.2.title': 'Scalable Solutions',
      'about.roadmap.2.desc': 'Built with scalability and security in mind, handling everything from local tournaments to large-scale international events.',
      'about.roadmap.3.title': 'Seamless Registration',
      'about.roadmap.3.desc': 'Effortless online registration, category selection, and secure payment processing for a worry-free experience.',
      'about.roadmap.4.title': 'Real-Time Management',
      'about.roadmap.4.desc': 'Instant access to participant information and data management for efficient, millisecond-perfect coordination.',
      'about.roadmap.5.title': 'Dynamic Scheduling',
      'about.roadmap.5.desc': 'Automated notifications and real-time schedule tracking to keep organizers and participants perfectly in sync.',
      'about.roadmap.6.title': 'Insights & Analytics',
      'about.roadmap.6.desc': 'Powerful tools for analyzing registration trends and event performance to ensure every second counts.',
      'login.title': 'WELCOME BACK',
      'login.subtitle': 'Sign in to access your track performance and upcoming races.',
      'login.google': 'Continue with Google',
      'login.or': 'OR CONTINUE WITH',
      'login.email': 'Email Address',
      'login.password': 'Password',
      'login.signin': 'Sign In',
      'login.no_account': "Don't have an account?",
      'login.signup': 'Sign Up',
      'login.organizer_title': 'ORGANIZER ACCESS',
      'login.organizer_warning': 'This section is strictly for authorized organizers only.',
      'signup.title': 'CREATE ACCOUNT',
      'signup.subtitle': 'Join the track and start dominating the field.',
      'signup.name': 'Full Name',
      'signup.already': 'Already have an account?',
      'signup.button': 'Create Account',
      'login.forgot': 'Forgot Password?',
      'login.full_name': 'Full Name',
      'login.confirm_password': 'Confirm Password',
      'forgot.back': 'Back to Login',
      'about.hero.title': 'ABOUT TIME TRACK',
      'about.intel.title': 'Intelligence Overview',
      'about.intel.desc': 'Time Track Solutions is a modern sports event management platform focused on simplifying registrations and operations.',
      'about.intel.quote': 'We provide a secure, scalable, and user-friendly system that helps organizers efficiently manage events while delivering a smooth experience for participants and teams.',
      'about.hierarchy.title': 'Operational Hierarchy',
      'about.hierarchy.subtitle': 'Permission-Based Access Protocol',
      'about.features.title': 'Feature Arsenal',
      'about.features.subtitle': 'Strategic Service Breakdown',
      'contact.hero.title': 'Get in Touch',
      'contact.hero.desc': 'Have questions about timing your next event? Reach out to our technical team.',
      'results.hero.title': 'Race Results',
      'results.hero.desc': 'Search and view official results for past events timed by Time Track. Find your rank, split times, and certificates.',
      'results.search.placeholder': 'SEARCH BY EVENT NAME OR BIB NUMBER...',
      'results.view.board': 'View Official Board'
    },
    BM: {
      'nav.home': 'LAMAN UTAMA',
      'nav.events': 'ACARA',
      'nav.results': 'KEPUTUSAN',
      'nav.about': 'TENTANG KAMI',
      'nav.contact': 'HUBUNGI KAMI',
      'nav.login': 'LOG MASUK',
      'nav.signup': 'DAFTAR',
      'nav.cart': 'TROLI SAYA',
      'hero.subtitle': 'IKUTI KAMI UNTUK LEBIH BANYAK ACARA SUKAN AKAN DATANG',
      'hero.title1': 'SETIAP',
      'hero.title2': 'SAAT',
      'hero.title3': 'BERHARGA',
      'hero.desc': 'Time Track menyediakan perkhidmatan masa sukan dan pengurusan acara terbaik di Malaysia. Kecemerlangan dalam setiap milisaat.',
      'hero.cta1': 'Acara Akan Datang',
      'hero.cta2': 'Log Masuk',
      'marquee.text': 'CONTOH',
      'events.reg_open': 'Pendaftaran Dibuka',
      'events.upcoming': 'ACARA',
      'events.events': 'MENDATANG',
      'events.desc': 'Tempah slot anda dalam perlumbaan yang paling dinantikan pada 2026. Kecemerlangan dalam masa, koordinasi, dan pengalaman atlet.',
      'events.archive': 'ARKIB',
      'events.archive_span': 'ACARA',
      'events.view_more': 'Lihat Lebih Banyak Acara',
      'events_page.title1': 'KALENDAR',
      'events_page.title2': 'ACARA',
      'events_page.desc': 'Temui cabaran akan datang dan hayati semula pencapaian utama. Gunakan portal pendaftaran rasmi kami untuk menempah slot anda.',
      'about.hero.story': 'Kisah Kami',
      'about.hero.title1': 'MEMACU',
      'about.hero.title2': 'PRESTASI',
      'about.hero.desc': 'Di Time Track Solution, kami berdedikasi untuk memudahkan sukan melalui teknologi. Kami menyediakan portal yang teguh dan mesra pengguna yang direka untuk memudahkan perjalanan dari pendaftaran hingga ke garis penamat.',
      'about.cta.title': 'BOLEH SKALA. SELAMAT.',
      'about.cta.title_span': 'TIDAK TERGUGAT.',
      'about.cta.button': 'SERTAI KAMI',
      'footer.explore': 'Teroka',
      'footer.policy': 'Polisi Kami',
      'footer.copyright': 'Hak Cipta ©2026 Time Track | Semua Hak Terpelihara',
      'card.open': 'Buka',
      'card.archived': 'Arkib',
      'card.reg_now': 'Daftar Sekarang',
      'card.archive_only': 'Arkib Sahaja',
      'card.reg_closed': 'Pendaftaran Ditutup',
      'home.precision': 'Ketepatan Kilat',
      'home.precision_desc': 'Menyediakan catatan masa milisaat paling tepat menggunakan teknologi RFID terkemuka industri.',
      'home.mgmt': 'Pengurusan Acara',
      'home.mgmt_desc': "Dari pendaftaran hingga ke garis penamat, kami memastikan pengalaman yang lancar untuk penganjur dan atlet.",
      'home.results': 'Perkhidmatan Keputusan',
      'home.results_desc': 'Penjejakan langsung segera dan keputusan digital yang diperakui tersedia serta-merta selepas tamat.',
      'home.ready': 'SEDIA UNTUK',
      'home.dominate': 'MENGUASAI',
      'home.field': 'PADANG?',
      'contact.title': 'HUBUNGI KAMI',
      'contact.subtitle': 'ADA PERTANYAAN? PASUKAN KAMI SEDIA MEMBANTU ANDA.',
      'contact.name': 'Nama',
      'contact.email': 'E-mel',
      'contact.message': 'Mesej',
      'contact.send': 'Hantar Mesej',
      'loading.status': 'Status_Sistem: Optimum',
      'loading.init': 'Memulakan Sistem',
      'about.roadmap.1.title': 'Inovasi Bersemangat',
      'about.roadmap.1.desc': 'Memudahkan proses pendaftaran acara sukan dengan teknologi terkini yang direka khas untuk atlet moden.',
      'about.roadmap.2.title': 'Penyelesaian Boleh Skala',
      'about.roadmap.2.desc': 'Dibina dengan skala dan keselamatan dalam fikiran, mengendalikan segala-galanya dari kejohanan tempatan hingga acara antarabangsa berskala besar.',
      'about.roadmap.3.title': 'Pendaftaran Lancar',
      'about.roadmap.3.desc': 'Pendaftaran dalam talian yang mudah, pemilihan kategori, dan pemprosesan pembayaran yang selamat untuk pengalaman tanpa bimbang.',
      'about.roadmap.4.title': 'Pengurusan Masa Nyata',
      'about.roadmap.4.desc': 'Akses segera kepada maklumat peserta dan pengurusan data untuk koordinasi yang tepat pada milisaat.',
      'about.roadmap.5.title': 'Penjadualan Dinamik',
      'about.roadmap.5.desc': 'Pemberitahuan automatik dan penjejakan jadual masa nyata untuk memastikan penganjur dan peserta sentiasa selari.',
      'about.roadmap.6.title': 'Wawasan & Analitik',
      'about.roadmap.6.desc': 'Alatan berkuasa untuk menganalisis trend pendaftaran dan prestasi acara bagi memastikan setiap saat berharga.',
      'login.title': 'SELAMAT KEMBALI',
      'login.subtitle': 'Log masuk untuk akses prestasi larian dan acara akan datang anda.',
      'login.google': 'Teruskan dengan Google',
      'login.or': 'ATAU TERUSKAN DENGAN',
      'login.email': 'Alamat Emel',
      'login.password': 'Kata Laluan',
      'login.signin': 'Log Masuk',
      'login.no_account': "Tiada akaun?",
      'login.signup': 'Daftar Sekarang',
      'login.organizer_title': 'AKSES PENGANJUR',
      'login.organizer_warning': 'Bahagian ini terhad kepada penganjur yang sah sahaja.',
      'signup.title': 'DAFTAR AKAUN',
      'signup.subtitle': 'Sertai larian dan mula menguasai padang.',
      'signup.name': 'Nama Penuh',
      'signup.already': 'Sudah mempunyai akaun?',
      'signup.button': 'Daftar Sekarang',
      'login.forgot': 'Lupa Kata Laluan?',
      'login.full_name': 'Nama Penuh',
      'login.confirm_password': 'Sahkan Kata Laluan',
      'forgot.back': 'Kembali ke Log Masuk',
      'about.hero.title': 'TENTANG TIME TRACK',
      'about.intel.title': 'Gambaran Kecerdasan',
      'about.intel.desc': 'Time Track Solutions adalah platform pengurusan acara sukan moden yang fokus untuk memudahkan pendaftaran dan operasi.',
      'about.intel.quote': 'Kami menyediakan sistem yang selamat, boleh skala, dan mesra pengguna yang membantu penganjur menguruskan acara dengan cekap sambil memberikan pengalaman yang lancar untuk peserta dan pasukan.',
      'about.hierarchy.title': 'Hierarki Operasi',
      'about.hierarchy.subtitle': 'Protokol Akses Berasaskan Kebenaran',
      'about.features.title': 'Arsenal Ciri',
      'about.features.subtitle': 'Pecahan Perkhidmatan Strategik',
      'contact.hero.title': 'Hubungi Kami',
      'contact.hero.desc': 'Ada soalan tentang catatan masa acara anda yang seterusnya? Hubungi pasukan teknikal kami.',
      'results.hero.title': 'Keputusan Perlumbaan',
      'results.hero.desc': 'Cari dan lihat keputusan rasmi untuk acara lampau yang diuruskan oleh Time Track. Cari kedudukan, masa perantaraan, dan sijil anda.',
      'results.search.placeholder': 'CARI MENGIKUT NAMA ACARA ATAU NOMBOR BIB...',
      'results.view.board': 'Lihat Papan Rasmi'
    }
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
